# Generated by Django 3.2.5 on 2021-07-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_auto_20210727_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='Answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.solution'),
        ),
    ]
