# Generated by Django 3.2.5 on 2021-07-28 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_assigment_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigment',
            name='Answer',
        ),
        migrations.AddField(
            model_name='solution',
            name='ass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Application.assigment'),
            preserve_default=False,
        ),
    ]
