# Generated by Django 3.2.5 on 2021-07-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_auto_20210728_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
