# Generated by Django 3.2.5 on 2021-07-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_solution_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='ass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.assigment', unique=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='points',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
