# Generated by Django 3.2.5 on 2021-07-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_auto_20210728_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='ass',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application.assigment'),
        ),
    ]
