# Generated by Django 3.2.5 on 2021-07-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_alter_solution_ass'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='Course',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
