# Generated by Django 3.2.5 on 2021-07-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_assigment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigment',
            name='Course',
        ),
    ]
