# Generated by Django 3.2.5 on 2021-07-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_remove_assigment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Application.course'),
            preserve_default=False,
        ),
    ]
