# Generated by Django 3.2.5 on 2021-07-29 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_assigment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='ass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.assigment'),
        ),
    ]
