# Generated by Django 3.2.5 on 2021-07-29 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0015_alter_solution_ass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='user',
        ),
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
