# Generated by Django 3.2.5 on 2021-08-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0018_auto_20210816_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='Deadline',
            field=models.DateTimeField(),
        ),
    ]
