# Generated by Django 3.2.5 on 2021-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_alter_assigment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='file',
            field=models.FileField(default=1, upload_to='Documents'),
            preserve_default=False,
        ),
    ]
