# Generated by Django 3.2.5 on 2021-08-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0020_solution_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.CharField(max_length=1000),
        ),
    ]
