# Generated by Django 3.2.5 on 2021-08-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0028_remove_solution_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='file',
            field=models.FileField(default=None, upload_to='', null=True),
            preserve_default=False,
        ),
    ]
