# Generated by Django 3.2.5 on 2021-08-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0029_solution_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
