# Generated by Django 3.2.5 on 2021-08-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0030_alter_solution_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='file',
        ),
    ]
