# Generated by Django 3.2.5 on 2021-08-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_usertoken_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
